# SPDX-License-Identifier: GPL-3.0-or-later
"""CurveForge objects: mesh objects whose geometry is generated by a style."""

import time
import traceback

import bpy
import numpy as np
from bpy.props import BoolProperty, EnumProperty, FloatProperty, IntProperty, PointerProperty, StringProperty
from bpy.types import PropertyGroup

from . import instancer, meshio
from .compiler import Compiler
from .engine.generate import run
from .engine.mesh import Assembler
from .nodes import TREE_ID

# Objects (session uids) each CurveForge object depends on, filled by rebuild().
DEPENDENCIES = {}


def _changed(self, context):
    from . import live
    live.request(self.id_data)


def _weight_changed(self, context):
    from . import live
    uid = self.session_uid
    for obj in outputs(getattr(context, "scene", None)):
        if uid in DEPENDENCIES.get(obj.session_uid, ()):
            live.request(obj)


def _poll_style(self, tree):
    return tree.bl_idname == TREE_ID


class CF_ObjectSettings(PropertyGroup):
    enabled: BoolProperty(default=False)
    style: PointerProperty(name="Style", type=bpy.types.NodeTree, poll=_poll_style, update=_changed,
                           description="Node tree (style) that generates this object")
    live: BoolProperty(name="Live Update", default=True, update=_changed,
                       description="Rebuild automatically when the style, the curves or the segments change")
    display: EnumProperty(name="Display", items=[("FULL", "Geometry", "Full geometry"),
                                                 ("BOX", "Boxes", "Bounding boxes of the segments (fast)")],
                          default="FULL", update=_changed)
    update_on_frame: BoolProperty(name="Update on Frame Change", default=False,
                                  description="Rebuild on every frame (animated curves or parameters)")

    stat_segments: IntProperty(default=0)
    stat_verts: IntProperty(default=0)
    stat_faces: IntProperty(default=0)
    stat_time: FloatProperty(default=0.0)
    stat_truncated: BoolProperty(default=False)
    error: StringProperty(default="")


def is_output(obj):
    try:
        return obj is not None and obj.type == "MESH" and obj.cf_scatter.enabled
    except (ReferenceError, AttributeError):
        return False


def outputs(scene=None):
    objs = scene.objects if scene is not None else bpy.data.objects
    return [o for o in objs if is_output(o)]


def users_of(tree):
    return [o for o in bpy.data.objects if is_output(o) and o.cf_scatter.style == tree]


def rebuild(obj, depsgraph=None):
    """Regenerate the mesh of a CurveForge object. Returns True on success."""
    st = obj.cf_scatter
    t0 = time.perf_counter()
    if depsgraph is None:
        depsgraph = bpy.context.evaluated_depsgraph_get()
    deps = set()
    errors = []
    asm = Assembler()
    count = 0
    truncated = False
    weld = 0.0
    try:
        tree = st.style
        if tree is None:
            errors.append("Choose or create a style")
        else:
            comp = Compiler(tree, depsgraph, st.display)
            gens = comp.generators()
            if not gens:
                errors.append("The style has no enabled Linear Generator")
            inv = np.array(obj.matrix_world.inverted(), dtype=np.float64)
            cache = {}
            for gen in gens:
                n, trunc, _ = run(gen.jobs, gen.sources, gen.settings_for, gen.place, asm, inv,
                                  clip=gen.clip, seed=gen.seed, slice_cache=cache)
                count += n
                truncated = truncated or trunc
                weld = max(weld, gen.weld)
            errors.extend(comp.warnings)
            deps = {o.session_uid for o in comp.deps}
        mesh = asm.build()
        if obj.data.users > 1 and not obj.data.library:
            obj.data = obj.data.copy()
        meshio.write_mesh(obj.data, mesh)
        if weld > 0.0 and len(mesh.co) and not mesh.instances:
            meshio.weld(obj.data, weld)
        instancer.sync(obj, mesh.instances)
        st.stat_segments = count
        st.stat_verts = len(obj.data.vertices)
        st.stat_faces = len(obj.data.polygons)
        st.stat_truncated = truncated
        ok = True
    except Exception as exc:  # keep Blender responsive, report in the panel
        traceback.print_exc()
        errors.insert(0, "%s: %s" % (type(exc).__name__, exc))
        ok = False
    msg = " | ".join(dict.fromkeys(errors))
    if st.error != msg:
        st.error = msg
    st.stat_time = time.perf_counter() - t0
    DEPENDENCIES[obj.session_uid] = deps
    return ok


def release_styles():
    """Take the styles out of the dependency graphs before the node types go away.

    The ``style`` pointer makes every depsgraph keep an evaluated copy of the node
    tree, and Blender 4.2 crashes when it frees a copy whose node types were
    unregistered (disable the add-on, then open a file). Clearing the pointers
    through RNA rebuilds the relations; ``restore_styles`` puts them back as plain
    ID properties once the classes are unregistered.
    """
    from . import live
    held = []
    with live.suspended():
        for obj in bpy.data.objects:
            try:
                tree = obj.cf_scatter.style
                if tree is not None:
                    obj.cf_scatter.style = None
                    held.append((obj, tree))
            except (AttributeError, RuntimeError, TypeError, ReferenceError):  # e.g. linked data
                continue
        if held:
            for scene in bpy.data.scenes:
                for layer in scene.view_layers:
                    if layer.depsgraph is not None:
                        layer.update()
    return held


def restore_styles(held):
    for obj, tree in held:
        try:
            # Blender 5.0 keeps the data of add-on properties apart from custom properties.
            get = getattr(obj, "bl_system_properties_get", None)
            props = get() if get is not None else obj
            props["cf_scatter"]["style"] = tree
        except (KeyError, TypeError, ReferenceError):
            pass


classes = (CF_ObjectSettings,)


def register():
    for cls in classes:
        bpy.utils.register_class(cls)
    bpy.types.Object.cf_scatter = PointerProperty(type=CF_ObjectSettings)
    bpy.types.Object.cf_weight = FloatProperty(
        name="Weight", default=1.0, min=0.0, soft_max=10.0, update=_weight_changed,
        description="Probability weight when picked at random from a collection by a Segment node")


def unregister():
    del bpy.types.Object.cf_weight
    del bpy.types.Object.cf_scatter
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
